# current dirは".devcontainer/"

###proxy
#実行元の環境にHTTP_PROXY、HTTPS_PROXY、NO_PROXY、CLAUDE_PROXYを設定しておくこと
#プロキシ不要な場合は未設定でよい
services:
  workspace:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
        NO_PROXY: ${NO_PROXY:-}
        CLAUDE_PROXY: ${CLAUDE_PROXY:-}
    environment:
      ###claude
      CLAUDE_CONFIG_DIR: /home/node/.claude
      # プロキシや証明書抑制関係
      PYTHONWARNINGS: ignore:Unverified HTTPS request
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
      CLAUDE_PROXY: ${CLAUDE_PROXY:-}
    working_dir: /workspaces
    volumes:
      - ../:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/share/ca-certificates/:/usr/share/ca-certificates/
      - $HOME/.aws/:/home/node/.aws
      - claude-config:/home/node/.claude
    tty: true

volumes:
  claude-config:
    driver: local
